FROM apache/airflow:2.9.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    psycopg2-binary==2.9.9 \
    requests==2.31.0 \
    lightgbm==4.3.0 \
    scikit-learn==1.4.2 \
    pandas==2.2.2 \
    mlflow==2.13.0 \
    sqlalchemy==1.4.52